---
- name: Setup Docker and deploy Nginx with custom page
  hosts: web
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Add Docker GPG key securely
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Create HTML directory for Nginx
      file:
        path: /home/ubuntu/nginx-html
        state: directory
        mode: '0755'

    - name: Copy custom index.html to EC2
      copy:
        src: files/index.html
        dest: /home/ubuntu/nginx-html/index.html
        mode: '0644'

    - name: Run Nginx container with mounted HTML
      community.docker.docker_container:
        name: nginx-server
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
        volumes:
          - /home/ubuntu/nginx-html:/usr/share/nginx/html:ro
